site_name: Recursos DAM/DAW
site_url: https://jordicido.github.io/recursosDAMDAW
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# para poder poner código de programación:
markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
      line_numbers: true
      line_spans: true
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: admonition
          class: admonition
          format: !!python/name:pymdownx.superfences.fence_admonition_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_math_format